table orders
	lineageTag: 7d076f5f-9163-47b2-87ae-583a1444ed1b

	measure 'Avg Delivery Days' = AVERAGE ( orders_staging[Delivery Days] )
		lineageTag: fcd928ea-61d1-4555-a179-1f407872a6b6

	measure 'On Time Orders' =
			CALCULATE (
				COUNTROWS ( orders ),
				FILTER (
					orders,
					NOT ISBLANK ( orders[order_delivered_customer_date] )
						&& orders[order_delivered_customer_date] <= orders[order_estimated_delivery_date]
				)
			)
		formatString: 0
		lineageTag: 690eb36a-e129-4f03-856e-8280c14b0efb

	measure 'On Time Rate' = IF ( [Total Orders] = 0, BLANK ( ), [On Time Orders] / [Total Orders] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 42387240-ecc8-4aca-a3d8-16350fbed94f

	column order_id
		dataType: string
		lineageTag: 08264f8f-760e-43bc-a278-75a789ae8c3b
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: d500856e-e351-4cb4-9e93-b274e714ca30
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column 'Order Status ID'
		dataType: int64
		formatString: 0
		lineageTag: 284c3d0a-59c1-452f-80c8-42716e7a5f10
		summarizeBy: none
		sourceColumn: Order Status ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: afee7468-6cd0-4b21-8948-c7cd56f9d2ca
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: b5fa7532-1334-41e8-abb9-e7089e1ecbf4
			defaultHierarchy: LocalDateTable_0911fbd6-181b-4aa9-a4a8-7b8cdf18d11c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: a8a4a39a-249a-4b24-a16f-00a28954e043
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: bba8c133-1c3d-454d-a8ef-72bcbbc56cdb
			defaultHierarchy: LocalDateTable_a421a1e1-2bb3-4b70-b01b-a5f7b5d5f121.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b08ba7d6-3e70-4315-9922-ca5986b248cf
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 834b4ce8-7907-402b-8ec9-3a4a2cf2ad8f
			defaultHierarchy: LocalDateTable_729608d6-dc7e-46bb-9629-0f2f9bd8ddd0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d8e0f4e-a368-4fb3-b1bf-4fe1b9835eba
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: abe1414c-6f6c-4baf-b474-443722c4dc79
			defaultHierarchy: LocalDateTable_f6d3c641-4a12-48c4-ad8b-2dfaf705932a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4e79eb9f-d841-44f5-81b0-20106c533375
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: 67ba1793-ddfc-4ab8-89f3-aba74e3414dc
			defaultHierarchy: LocalDateTable_4b27f955-cae3-44a7-ab26-933eef0d0545.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: string
		lineageTag: 8ecd37ce-6497-460b-91ab-f78417fb14ca
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: string
		lineageTag: 5b2ca51a-297d-468e-af8a-8df90c3006f9
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	column order_weight_kg
		dataType: double
		lineageTag: cc2b2098-499f-413c-97ac-4c567bd09548
		summarizeBy: sum
		sourceColumn: order_weight_kg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_by
		dataType: string
		lineageTag: a5524c88-0992-4d5e-bc3d-68d25845c237
		summarizeBy: none
		sourceColumn: created_by

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		lineageTag: d581533d-9786-463f-9d88-670fb29e1a96
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = orders_staging,
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Index",{{"order_id", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"customer_id", type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Order Status", Int64.Type}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type2", "created_at", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"created_at.1", "created_at.2"}),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"created_at.1", type text}, {"created_at.2", type text}}),
				    #"Merged Columns" = Table.CombineColumns(#"Changed Type8",{"created_at.1", "created_at.2"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"created_at"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Merged Columns",{"Index", "order_id", "customer_id", "Order Status", "Order Date", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date", "created_at", "updated_at", "created_by"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each [Order Date] >= #datetime(2016, 1, 1, 0, 0, 0)),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Index"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Order Status"}, order_status_lookup, {"Order Status ID"}, "order_status_lookup", JoinKind.LeftOuter),
				    #"Expanded order_status_lookup" = Table.ExpandTableColumn(#"Merged Queries", "order_status_lookup", {"Order Status ID", "Order Status"}, {"order_status_lookup.Order Status ID", "order_status_lookup.Order Status"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded order_status_lookup",{"order_status_lookup.Order Status ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Order Status", "Order Status ID"}, {"order_status_lookup.Order Status", "Order Status"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

