table Product
	lineageTag: 12e6b085-8f32-47d1-9ab4-8f148a60829e

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 11675654-0722-4347-97e8-96e72751e28a
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: int64
		formatString: 0
		lineageTag: 4022ed68-528e-4ccd-9a29-260d2656a702
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 8683ea5a-1566-4299-b116-b6f825b502bd
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 5ad6e026-ea0d-4fe3-ad76-ca08fce5cc72
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 77c79aa5-1b73-4a4e-9f64-47b60ed36c1b
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 74322f51-3065-4baa-bbf8-43257bbb713b
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column WeightUnit
		dataType: string
		lineageTag: adf803a7-deab-483d-95c8-b82f207f60e3
		summarizeBy: none
		sourceColumn: WeightUnit

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 0a4db973-e85c-40d2-a2ba-4fbb9391869b
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		lineageTag: bc59fd08-7232-4aab-9b77-c8b612b4f5c0
		summarizeBy: none
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price
		dataType: double
		lineageTag: 2d23c370-c42a-4ed8-9123-b5460bb24f47
		summarizeBy: none
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 5e910527-85b8-468b-b5ef-fe60dee62c05
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 5ef63b8f-c564-4d1f-9b17-5221aecf6f38
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column SubCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: e969292c-28d7-41c9-b5aa-6f91b7d372a2
		summarizeBy: none
		sourceColumn: SubCategoryKey

		annotation SummarizationSetBy = Automatic

	column SubCategoryName
		dataType: string
		lineageTag: 06e278bf-e29d-42ec-b089-fccc3f7d4ca7
		summarizeBy: none
		sourceColumn: SubCategoryName

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		queryGroup: CSV
		source =
				let
				    Source = Source,
				    CSVData = Source{5}[CSVData],
				    #"Changed Type" = Table.TransformColumnTypes(CSVData,{{"ProductKey", Int64.Type}, {"ProductCode", Int64.Type}, {"ProductName", type text}, {"Manufacturer", type text}, {"Brand", type text}, {"Color", type text}, {"WeightUnit", type text}, {"Weight", type number}, {"Cost", type number}, {"Price", type number}, {"CategoryKey", Int64.Type}, {"CategoryName", type text}, {"SubCategoryKey", Int64.Type}, {"SubCategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

